"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SimulationParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SensorUnitsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Vector2: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Vector2 | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    BASE_POS_FIELD_NUMBER: builtins.int
    SENSOR_UNITS_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def base_pos(self) -> global___Vector2: ...
    @property
    def sensor_units(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Vector2]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        base_pos: global___Vector2 | None = ...,
        sensor_units: collections.abc.Mapping[builtins.str, global___Vector2] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["base_pos", b"base_pos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["base_pos", b"base_pos", "id", b"id", "sensor_units", b"sensor_units"]) -> None: ...

global___SimulationParameters = SimulationParameters

@typing.final
class UnitLaunched(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    POS_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def pos(self) -> global___Vector2: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        pos: global___Vector2 | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pos", b"pos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "pos", b"pos"]) -> None: ...

global___UnitLaunched = UnitLaunched

@typing.final
class Vector2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Vector2 = Vector2

@typing.final
class UnitCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ThrustCommand(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IMPULSE_FIELD_NUMBER: builtins.int
        @property
        def impulse(self) -> global___Vector2: ...
        def __init__(
            self,
            *,
            impulse: global___Vector2 | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["impulse", b"impulse"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["impulse", b"impulse"]) -> None: ...

    @typing.final
    class MsgCommand(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DST_FIELD_NUMBER: builtins.int
        MSG_FIELD_NUMBER: builtins.int
        dst: builtins.str
        @property
        def msg(self) -> google.protobuf.any_pb2.Any: ...
        def __init__(
            self,
            *,
            dst: builtins.str | None = ...,
            msg: google.protobuf.any_pb2.Any | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_dst", b"_dst", "dst", b"dst", "msg", b"msg"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_dst", b"_dst", "dst", b"dst", "msg", b"msg"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_dst", b"_dst"]) -> typing.Literal["dst"] | None: ...

    THRUST_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    @property
    def thrust(self) -> global___UnitCommand.ThrustCommand: ...
    @property
    def msg(self) -> global___UnitCommand.MsgCommand: ...
    def __init__(
        self,
        *,
        thrust: global___UnitCommand.ThrustCommand | None = ...,
        msg: global___UnitCommand.MsgCommand | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "msg", b"msg", "thrust", b"thrust"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "msg", b"msg", "thrust", b"thrust"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["command", b"command"]) -> typing.Literal["thrust", "msg"] | None: ...

global___UnitCommand = UnitCommand

@typing.final
class UnitStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POS_FIELD_NUMBER: builtins.int
    DETECTIONS_FIELD_NUMBER: builtins.int
    MESSAGES_FIELD_NUMBER: builtins.int
    @property
    def pos(self) -> global___Vector2: ...
    @property
    def detections(self) -> global___Detections: ...
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UnitMessage]: ...
    def __init__(
        self,
        *,
        pos: global___Vector2 | None = ...,
        detections: global___Detections | None = ...,
        messages: collections.abc.Iterable[global___UnitMessage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_detections", b"_detections", "detections", b"detections", "pos", b"pos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_detections", b"_detections", "detections", b"detections", "messages", b"messages", "pos", b"pos"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_detections", b"_detections"]) -> typing.Literal["detections"] | None: ...

global___UnitStatus = UnitStatus

@typing.final
class UnitMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SRC_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    src: builtins.str
    @property
    def value(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        src: builtins.str = ...,
        value: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["src", b"src", "value", b"value"]) -> None: ...

global___UnitMessage = UnitMessage

@typing.final
class Detections(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NORTH_FIELD_NUMBER: builtins.int
    NORTHEAST_FIELD_NUMBER: builtins.int
    EAST_FIELD_NUMBER: builtins.int
    SOUTHEAST_FIELD_NUMBER: builtins.int
    SOUTH_FIELD_NUMBER: builtins.int
    SOUTHWEST_FIELD_NUMBER: builtins.int
    WEST_FIELD_NUMBER: builtins.int
    NORTHWEST_FIELD_NUMBER: builtins.int
    @property
    def north(self) -> global___Detection: ...
    @property
    def northeast(self) -> global___Detection: ...
    @property
    def east(self) -> global___Detection: ...
    @property
    def southeast(self) -> global___Detection: ...
    @property
    def south(self) -> global___Detection: ...
    @property
    def southwest(self) -> global___Detection: ...
    @property
    def west(self) -> global___Detection: ...
    @property
    def northwest(self) -> global___Detection: ...
    def __init__(
        self,
        *,
        north: global___Detection | None = ...,
        northeast: global___Detection | None = ...,
        east: global___Detection | None = ...,
        southeast: global___Detection | None = ...,
        south: global___Detection | None = ...,
        southwest: global___Detection | None = ...,
        west: global___Detection | None = ...,
        northwest: global___Detection | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_east", b"_east", "_north", b"_north", "_northeast", b"_northeast", "_northwest", b"_northwest", "_south", b"_south", "_southeast", b"_southeast", "_southwest", b"_southwest", "_west", b"_west", "east", b"east", "north", b"north", "northeast", b"northeast", "northwest", b"northwest", "south", b"south", "southeast", b"southeast", "southwest", b"southwest", "west", b"west"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_east", b"_east", "_north", b"_north", "_northeast", b"_northeast", "_northwest", b"_northwest", "_south", b"_south", "_southeast", b"_southeast", "_southwest", b"_southwest", "_west", b"_west", "east", b"east", "north", b"north", "northeast", b"northeast", "northwest", b"northwest", "south", b"south", "southeast", b"southeast", "southwest", b"southwest", "west", b"west"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_east", b"_east"]) -> typing.Literal["east"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_north", b"_north"]) -> typing.Literal["north"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_northeast", b"_northeast"]) -> typing.Literal["northeast"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_northwest", b"_northwest"]) -> typing.Literal["northwest"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_south", b"_south"]) -> typing.Literal["south"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_southeast", b"_southeast"]) -> typing.Literal["southeast"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_southwest", b"_southwest"]) -> typing.Literal["southwest"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_west", b"_west"]) -> typing.Literal["west"] | None: ...

global___Detections = Detections

@typing.final
class Detection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Class:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Detection._Class.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OBSTACLE: Detection._Class.ValueType  # 0
        TARGET: Detection._Class.ValueType  # 1

    class Class(_Class, metaclass=_ClassEnumTypeWrapper): ...
    OBSTACLE: Detection.Class.ValueType  # 0
    TARGET: Detection.Class.ValueType  # 1

    CLASS_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    distance: builtins.float
    def __init__(
        self,
        *,
        distance: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["class", b"class", "distance", b"distance"]) -> None: ...

global___Detection = Detection

@typing.final
class SimulationStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SimulationStatus._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RUNNING: SimulationStatus._Status.ValueType  # 0
        SUCCESS: SimulationStatus._Status.ValueType  # 1
        TIMED_OUT: SimulationStatus._Status.ValueType  # 2
        CANCELED: SimulationStatus._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    RUNNING: SimulationStatus.Status.ValueType  # 0
    SUCCESS: SimulationStatus.Status.ValueType  # 1
    TIMED_OUT: SimulationStatus.Status.ValueType  # 2
    CANCELED: SimulationStatus.Status.ValueType  # 3

    STATUS_FIELD_NUMBER: builtins.int
    status: global___SimulationStatus.Status.ValueType
    def __init__(
        self,
        *,
        status: global___SimulationStatus.Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___SimulationStatus = SimulationStatus
